apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-csharp
  namespace: argocd-lab
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-csharp
  template:
    metadata:
      labels:
        app: api-csharp
    spec:
      containers:
        - image: ghcr.io/guitarrapc/argocd-lab:latest-csharp
          name: api-csharp
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go
  namespace: argocd-lab
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-go
  template:
    metadata:
      labels:
        app: api-go
    spec:
      containers:
        - image: ghcr.io/guitarrapc/argocd-lab:latest-go
          name: api-go
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
