# no namespace declared here for argocd to manage it
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-csharp
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api-csharp
    app.kubernetes.io/part-of: api-application
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-csharp
  template:
    metadata:
      labels:
        app: api-csharp
    spec:
      containers:
        - name: api-csharp
          image: ghcr.io/guitarrapc/argocd-lab:latest-csharp
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-go
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api-go
    app.kubernetes.io/part-of: api-application
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-go
  template:
    metadata:
      labels:
        app: api-go
    spec:
      containers:
        - name: api-go
          image: ghcr.io/guitarrapc/argocd-lab:latest-go
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
# no namespace declared here for argocd to manage it
apiVersion: v1
kind: Service
metadata:
  name: api-csharp-svc
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api-csharp
    app.kubernetes.io/part-of: api-application
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: api-csharp
---
apiVersion: v1
kind: Service
metadata:
  name: api-go-svc
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api-go
    app.kubernetes.io/part-of: api-application
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: api-go
