apiVersion: v1
kind: Service
metadata:
  name: api-csharp-svc
  namespace: argocd-lab
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: api-csharp
---
apiVersion: v1
kind: Service
metadata:
  name: api-go-svc
  namespace: argocd-lab
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: api-go
