# kubectl apply -f k8s/kustomize-application.yaml -n argocd
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-lab
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/guitarrapc/argocd-lab.git
    targetRevision: main
    path: k8s/kustomize-api
  destination:
    name: in-cluster # Rename to actual cluster name if needed
    namespace: argocd-lab
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
