nameOverride: ""
replicaCount: 1
image:
  repository: ghcr.io/guitarrapc/argocd-lab
  tagCsharp: v0.2.0-csharp
  tagGo: v0.2.0-go
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80

resources: {}
# resources:
#   limits:
#     memory: 128Mi
#     cpu: 500m
#   requests:
#     memory: 128Mi
#     cpu: 250m

nodeSelector: {}
tolerations: []
affinity: {}
