# no namespace declared here for argocd to manage it
apiVersion: v1
kind: Service
metadata:
  name: api-csharp-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: api-csharp
---
apiVersion: v1
kind: Service
metadata:
  name: api-go-svc
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: api-go
