# no namespace declared here for argocd to manage it
apiVersion: v1
kind: Service
metadata:
  name: api-csharp-svc
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api-csharp
    app.kubernetes.io/part-of: api-application
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: api-csharp
---
apiVersion: v1
kind: Service
metadata:
  name: api-go-svc
  labels:
    app.kubernetes.io/name: api
    app.kubernetes.io/component: api-go
    app.kubernetes.io/part-of: api-application
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
  selector:
    app: api-go
